# -*- coding: utf-8 -*-
"""AI_Meeting_Action_Item_Extractor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15578lI7YVyUzH5jDPuAJGlvaj57mV4Fb
"""

!pip install spacy pandas
!python -m spacy download en_core_web_sm

import pandas as pd
import spacy
import re

print("Libraries imported successfully!")

nlp = spacy.load("en_core_web_sm")

print("spaCy model loaded successfully!")

data = {
    "meeting_id": [
        "M001",
        "M002",
        "M003",
        "M004",
        "M005"
    ],

    "meeting_text": [
        "Ashwini will complete the dataset by Friday.",
        "Akalya will prepare the model documentation by Monday.",
        "Divya will create the presentation by Wednesday.",
        "Abinaya must fix the login issue tomorrow.",
        "The team should test the application next Monday."
    ],

    "person": [
        "Ashwini",
        "Akalya",
        "Divya",
        "abinaya",
        "Team"
    ],

    "action_item": [
        "Complete the dataset",
        "Prepare the model documentation",
        "Create the presentation",
        "Fix the login issue",
        "Test the application"
    ],

    "deadline": [
        "Friday",
        "Monday",
        "Wednesday",
        "Tomorrow",
        "Next Monday"
    ],

    "priority": [
        "Medium",
        "Medium",
        "Medium",
        "High",
        "High"
    ]
}

df = pd.DataFrame(data)

df



print("Rows:", len(df))
print("Columns:", df.columns.tolist())

def preprocess_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z\s]', '', text)

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

df["clean_text"] = df["meeting_text"].apply(preprocess_text)

df[["meeting_text", "clean_text"]]

def extract_person(text):
    # Take the first word of the sentence
    first_word = text.strip().split()[0]

    # Remove punctuation
    first_word = re.sub(r'[^A-Za-z]', '', first_word)

    # If sentence starts with "The", it is a team task
    if first_word.lower() in ["the", "team"]:
        return "Team"

    return first_word

df["extracted_person"] = df["meeting_text"].apply(extract_person)

df[["meeting_text", "extracted_person"]]

import re

def extract_deadline(text):

    # Pattern: by Friday / by Monday
    match = re.search(r'\bby\s+([A-Za-z]+)', text, re.IGNORECASE)
    if match:
        return match.group(1)

    # Pattern: before Friday / before Monday
    match = re.search(r'\bbefore\s+([A-Za-z]+)', text, re.IGNORECASE)
    if match:
        return match.group(1)

    # Pattern: tomorrow
    if re.search(r'\btomorrow\b', text, re.IGNORECASE):
        return "Tomorrow"

    # Pattern: next Monday / next Friday
    match = re.search(r'\bnext\s+([A-Za-z]+)', text, re.IGNORECASE)
    if match:
        return "Next " + match.group(1)

    return "Not specified"

df["extracted_deadline"] = df["meeting_text"].apply(extract_deadline)

df[["meeting_text", "extracted_deadline"]]

def extract_action(text):

    # Remove deadline part
    text = re.sub(
        r'\b(by|before)\s+[A-Za-z]+',
        '',
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r'\btomorrow\b',
        '',
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r'\bnext\s+[A-Za-z]+',
        '',
        text,
        flags=re.IGNORECASE
    )

    # Remove person's name
    words = text.strip().split()

    if len(words) > 1:
        text = " ".join(words[1:])

    # Remove helping words
    text = re.sub(
        r'\b(will|must|should|need to)\b',
        '',
        text,
        flags=re.IGNORECASE
    )

    # Remove extra spaces and punctuation
    text = re.sub(r'[.]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    # Capitalize first letter
    return text.capitalize()

df["extracted_action"] = df["meeting_text"].apply(extract_action)

df[["meeting_text", "extracted_action"]]

def extract_priority(text):

    text = text.lower()

    # High priority words
    if any(word in text for word in [
        "must", "urgent", "critical", "immediately", "asap"
    ]):
        return "High"

    # Medium priority words
    elif any(word in text for word in [
        "should", "need to", "important"
    ]):
        return "Medium"

    # Default
    else:
        return "Low"

df["extracted_priority"] = df["meeting_text"].apply(extract_priority)

df[["meeting_text", "extracted_priority"]]

final_df = df[
    [
        "extracted_person",
        "extracted_action",
        "extracted_deadline",
        "extracted_priority"
    ]
]

final_df.columns = [
    "Person",
    "Action Item",
    "Deadline",
    "Priority"
]

final_df

new_meeting = """
Karthik must complete the project report by Friday.
"""

person = extract_person(new_meeting)
action = extract_action(new_meeting)
deadline = extract_deadline(new_meeting)
priority = extract_priority(new_meeting)

print("Person:", person)
print("Action Item:", action)
print("Deadline:", deadline)
print("Priority:", priority)

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import re
# 
# st.title("🤖 AI Meeting Action-Item Extractor")
# 
# st.write("Enter your meeting transcript below:")
# 
# meeting_text = st.text_area(
#     "Meeting Transcript",
#     placeholder="Example: Akalya will complete the project report by Friday."
# )
# 
# def extract_person(text):
#     first_word = text.strip().split()[0]
#     first_word = re.sub(r'[^A-Za-z]', '', first_word)
# 
#     if first_word.lower() in ["the", "team"]:
#         return "Team"
# 
#     return first_word
# 
# 
# def extract_deadline(text):
# 
#     match = re.search(
#         r'\bby\s+([A-Za-z]+)',
#         text,
#         re.IGNORECASE
#     )
# 
#     if match:
#         return match.group(1)
# 
#     if re.search(r'\btomorrow\b', text, re.IGNORECASE):
#         return "Tomorrow"
# 
#     match = re.search(
#         r'\bnext\s+([A-Za-z]+)',
#         text,
#         re.IGNORECASE
#     )
# 
#     if match:
#         return "Next " + match.group(1)
# 
#     return "Not specified"
# 
# 
# def extract_action(text):
# 
#     text = re.sub(
#         r'\b(by|before)\s+[A-Za-z]+',
#         '',
#         text,
#         flags=re.IGNORECASE
#     )
# 
#     text = re.sub(
#         r'\btomorrow\b',
#         '',
#         text,
#         flags=re.IGNORECASE
#     )
# 
#     text = re.sub(
#         r'\bnext\s+[A-Za-z]+',
#         '',
#         text,
#         flags=re.IGNORECASE
#     )
# 
#     words = text.strip().split()
# 
#     if len(words) > 1:
#         text = " ".join(words[1:])
# 
#     text = re.sub(
#         r'\b(will|must|should|need to)\b',
#         '',
#         text,
#         flags=re.IGNORECASE
#     )
# 
#     text = re.sub(r'[.]', '', text)
#     text = re.sub(r'\s+', ' ', text).strip()
# 
#     return text.capitalize()
# 
# 
# def extract_priority(text):
# 
#     text = text.lower()
# 
#     if any(word in text for word in [
#         "must", "urgent", "critical", "immediately", "asap"
#     ]):
#         return "High"
# 
#     elif any(word in text for word in [
#         "should", "need to", "important"
#     ]):
#         return "Medium"
# 
#     return "Low"
# 
# 
# if st.button("Extract Action Item"):
# 
#     if meeting_text.strip():
# 
#         person = extract_person(meeting_text)
#         action = extract_action(meeting_text)
#         deadline = extract_deadline(meeting_text)
#         priority = extract_priority(meeting_text)
# 
#         st.subheader("📋 Extracted Action Item")
# 
#         st.write("**Person:**", person)
#         st.write("**Action Item:**", action)
#         st.write("**Deadline:**", deadline)
#         st.write("**Priority:**", priority)
# 
#     else:
#         st.warning("Please enter a meeting transcript.")

!streamlit run app.py &>/content/logs.txt &

!cat /content/logs.txt

!pkill -f ngrok
!pkill -f streamlit

!streamlit run app.py --server.port 8501 &>/content/logs.txt &

new_meeting = "Priya must submit the project report by Friday."

person = extract_person(new_meeting)
action = extract_action(new_meeting)
deadline = extract_deadline(new_meeting)
priority = extract_priority(new_meeting)

result = {
    "Person": person,
    "Action Item": action,
    "Deadline": deadline,
    "Priority": priority
}

result

def process_meeting(text):
    return {
        "Person": extract_person(text),
        "Action Item": extract_action(text),
        "Deadline": extract_deadline(text),
        "Priority": extract_priority(text)
    }

meetings = [
    "Priya must submit the project report by Friday.",
    "Rahul will complete the dataset by Monday.",
    "Sneha should prepare the presentation by Wednesday.",
    "Arun must fix the login problem tomorrow.",
    "The team should test the application next Monday."
]

results = []

for meeting in meetings:
    result = process_meeting(meeting)
    results.append(result)

final_results = pd.DataFrame(results)

final_results

final_results.to_csv(
    "meeting_action_items.csv",
    index=False
)

print("CSV file created successfully!")

sample_data = pd.DataFrame({
    "meeting_text": [
        "Priya must submit the project report by Friday.",
        "Rahul will complete the dataset by Monday.",
        "Sneha should prepare the presentation by Wednesday.",
        "Arun must fix the login problem tomorrow.",
        "The team should test the application next Monday."
    ]
})

sample_data.to_csv("meeting_input.csv", index=False)

print("Sample CSV created successfully!")

input_df = pd.read_csv("meeting_input.csv")

input_df

results = []

for text in input_df["meeting_text"]:

    result = process_meeting(text)

    results.append(result)

output_df = pd.DataFrame(results)

output_df

output_df.to_csv(
    "final_meeting_action_items.csv",
    index=False
)

print("Final CSV created successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import re
# 
# st.set_page_config(
#     page_title="AI Meeting Action-Item Extractor",
#     page_icon="🤖",
#     layout="wide"
# )
# 
# st.title("🤖 AI Meeting Action-Item Extractor")
# 
# st.write(
#     "Extract Person, Action Item, Deadline and Priority "
#     "from meeting transcripts."
# )
# 
# 
# # -----------------------------
# # Person Extraction
# # -----------------------------
# 
# def extract_person(text):
# 
#     first_word = text.strip().split()[0]
# 
#     first_word = re.sub(
#         r'[^A-Za-z]',
#         '',
#         first_word
#     )
# 
#     if first_word.lower() in ["the", "team"]:
#         return "Team"
# 
#     return first_word
# 
# 
# # -----------------------------
# # Deadline Extraction
# # -----------------------------
# 
# def extract_deadline(text):
# 
#     match = re.search(
#         r'\bby\s+([A-Za-z]+)',
#         text,
#         re.IGNORECASE
#     )
# 
#     if match:
#         return match.group(1)
# 
#     if re.search(
#         r'\btomorrow\b',
#         text,
#         re.IGNORECASE
#     ):
#         return "Tomorrow"
# 
#     match = re.search(
#         r'\bnext\s+([A-Za-z]+)',
#         text,
#         re.IGNORECASE
#     )
# 
#     if match:
#         return "Next " + match.group(1)
# 
#     return "Not specified"
# 
# 
# # -----------------------------
# # Action Extraction
# # -----------------------------
# 
# def extract_action(text):
# 
#     text = re.sub(
#         r'\b(by|before)\s+[A-Za-z]+',
#         '',
#         text,
#         flags=re.IGNORECASE
#     )
# 
#     text = re.sub(
#         r'\btomorrow\b',
#         '',
#         text,
#         flags=re.IGNORECASE
#     )
# 
#     text = re.sub(
#         r'\bnext\s+[A-Za-z]+',
#         '',
#         text,
#         flags=re.IGNORECASE
#     )
# 
#     words = text.strip().split()
# 
#     if len(words) > 1:
#         text = " ".join(words[1:])
# 
#     text = re.sub(
#         r'\b(will|must|should|need to)\b',
#         '',
#         text,
#         flags=re.IGNORECASE
#     )
# 
#     text = re.sub(
#         r'[.]',
#         '',
#         text
#     )
# 
#     text = re.sub(
#         r'\s+',
#         ' ',
#         text
#     ).strip()
# 
#     return text.capitalize()
# 
# 
# # -----------------------------
# # Priority Extraction
# # -----------------------------
# 
# def extract_priority(text):
# 
#     text = text.lower()
# 
#     if any(word in text for word in [
#         "must",
#         "urgent",
#         "critical",
#         "immediately",
#         "asap"
#     ]):
#         return "High"
# 
#     elif any(word in text for word in [
#         "should",
#         "need to",
#         "important"
#     ]):
#         return "Medium"
# 
#     return "Low"
# 
# 
# # -----------------------------
# # Process Meeting
# # -----------------------------
# 
# def process_meeting(text):
# 
#     return {
#         "Person": extract_person(text),
#         "Action Item": extract_action(text),
#         "Deadline": extract_deadline(text),
#         "Priority": extract_priority(text)
#     }
# 
# 
# # -----------------------------
# # Input Section
# # -----------------------------
# 
# st.subheader("📝 Enter Meeting Transcript")
# 
# meeting_text = st.text_area(
#     "Meeting Transcript",
#     placeholder=(
#         "Example: Priya must submit the project report "
#         "by Friday."
#     )
# )
# 
# 
# # -----------------------------
# # Extract Button
# # -----------------------------
# 
# if st.button("🚀 Extract Action Item"):
# 
#     if meeting_text.strip():
# 
#         result = process_meeting(meeting_text)
# 
#         result_df = pd.DataFrame([result])
# 
#         st.subheader("📋 Extracted Result")
# 
#         st.dataframe(
#             result_df,
#             use_container_width=True
#         )
# 
#         csv = result_df.to_csv(
#             index=False
#         )
# 
#         st.download_button(
#             "⬇️ Download Result",
#             csv,
#             "meeting_action_item.csv",
#             "text/csv"
#         )
# 
#     else:
# 
#         st.warning(
#             "Please enter a meeting transcript."
#         )

!ls -l app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas

!ls

from google.colab import files

files.download("app.py")
files.download("requirements.txt")

!pkill -f streamlit
!pkill -f ngrok

!pip install -q streamlit

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

!streamlit run app.py --server.address 0.0.0.0 --server.port 8501 > /content/streamlit.log 2>&1 &

!./cloudflared tunnel --url http://localhost:8501

!pip install -q streamlit

!pkill -f streamlit
!streamlit run app.py --server.address 0.0.0.0 --server.port 8501 > /content/streamlit.log 2>&1 &